services:
  - type: web
    name: illuminator-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000
      - key: BREVO_API_KEY
        sync: false # Set this in Render Dashboard
